title: "Daniel Diurczak"
email: "daniel.diurczak@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  FIXME
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: DanielDiurczak
github_username: ddiurcza2

# Build settings
plugins:
  - jekyll-feed
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache