title: "Daniel Diurczak"
email: "daniel.diurczak@gmail.com"
description: 

baseurl: /ddiurcza2.github.io
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: DanielDiurczak
github_username: ddiurcza2

# Build settings
plugins:
  - jekyll-feed
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache
